### ISSUE TITLE
CustomTabs integration broken on Android 7.1.1

### ISSUE THREAD

**Issue by mbruggmann** [spotify/android-auth#16]
I'm getting the following crash when using the `android-auth` SDK on an emulator with API version 25 (Android 7.1.1). The same application works on a api 24 emulator.

Backtrace (slightly redacted):
```bash
D/com.spotify.sdk.android.authentication.LoginActivity: https://accounts.spotify.com/authorize?client_id=CLIENTID&response_type=token&redirect_uri=CALLBACK&show_dialog=false&utm_source=spotify-sdk&utm_medium=android-sdk&utm_campaign=android-sdk&scope=SCOPES
D/SpotifyAuthHandler: start
D/SpotifyAuthHandler: stop
D/AndroidRuntime: Shutting down VM


                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: APP, PID: PID
                  java.lang.NoSuchMethodError: No virtual method launchUrl(Landroid/app/Activity;Landroid/net/Uri;)V in class Landroid/support/customtabs/CustomTabsIntent; or its super classes (declaration of 'android.support.customtabs.CustomTabsIntent' appears in /data/app/package/base.apk)
                      at com.spotify.sdk.android.authentication.CustomTabAuthHandler.start(CustomTabAuthHandler.java:73)
                      at com.spotify.sdk.android.authentication.AuthenticationClient.tryAuthenticationHandler(AuthenticationClient.java:503)
                      at com.spotify.sdk.android.authentication.AuthenticationClient.authenticate(AuthenticationClient.java:428)
                      at com.spotify.sdk.android.authentication.LoginActivity.onCreate(LoginActivity.java:112)
                      at android.app.Activity.performCreate(Activity.java:6679)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by jtvd78** [comment]
I had this same problem, and I believe I've made some progress on the issue. I looked into the source for this library, and I found out that they're building the project with customtabs:25.1.1. But, whenever I tried to add that version of chrometabs as a dependency in my project, Android Studio would claim that it could not find the version. So, I downloaded the source, changed the dependency version of chrometabs to 25.1.0, and now the chrome page opens without crashing. 

I am still having a problem, however, in that the page that opens up in the custom chrome tab is all white, with no content. 

Here is what I compiled, if you'd rather just download it here than build it yourself. 
[spotify-android-auth-1.0.0.zip](https://github.com/spotify/android-auth/files/801646/spotify-android-auth-1.0.0.zip)
