### ISSUE TITLE
NullPointerException - reports from users

### ISSUE THREAD

**Issue by kenumir** [spotify/android-auth#29]
Receives reports from the users from the application in the play store app.
Stack trace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{<myapp>/com.spotify.sdk.android.authentication.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
       at android.content.IntentFilter.getDataAuthority(IntentFilter.java:1063)
       at com.spotify.sdk.android.authentication.CustomTabAuthHandler.hasCustomTabRedirectActivity(CustomTabAuthHandler.java)
       at com.spotify.sdk.android.authentication.CustomTabAuthHandler.start(CustomTabAuthHandler.java)
       at com.spotify.sdk.android.authentication.AuthenticationClient.tryAuthenticationHandler(AuthenticationClient.java)
       at com.spotify.sdk.android.authentication.AuthenticationClient.authenticate(AuthenticationClient.java)
       at com.spotify.sdk.android.authentication.LoginActivity.onCreate(LoginActivity.java)
       at android.app.Activity.performCreate(Activity.java:6272)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
       at android.app.ActivityThread.access$900(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

Its came from various devices but cannot reproduce this exception.

**Comment by petergayduchik** [comment]
its error in your code

**Comment by kenumir** [comment]
I do not think so, after my fast investigation, https://github.com/spotify/android-auth/blob/master/auth-lib/src/main/java/com/spotify/sdk/android/authentication/CustomTabAuthHandler.java#L122

`ActivityInfo ai = infos.get(0).activityInfo;`

Getting element from array without any check

**Comment by hughrawlinson** [comment]
Hey @kenumir - the check is above: https://github.com/spotify/android-auth/blob/master/auth-lib/src/main/java/com/spotify/sdk/android/authentication/CustomTabAuthHandler.java#L115

**Comment by kenumir** [comment]
@hughrawlinson checks only size != 1 in case `infos` is empty, we have exception.

**Comment by JanStoltman** [comment]
@kenumir In case `infos` is empty, it's size != 1 so `ActivityInfo ai = infos.get(0).activityInfo;` wouldn't get executed, instead `hasCustomTabRedirectActivity` would return false.
